### ISSUE TITLE
discord-bot-exe: Maybe.fromJust: Nothing

### ISSUE THREAD

**Issue by SadPandaBear** [BorisNikulin/discord-bot#1]
Tried running the example you provided (based on [discord-hs](https://github.com/jano017/Discord.hs)), but unfortunately got that message.

Seems that changing [this line](https://github.com/BorisNikulin/discord-bot/blob/master/app/Main.hs#L22) to something like `token <- readFile "secrets/bot-token"` works as expected.

**Comment by BorisNikulin** [comment]
"Works on my machine"
However, I suspect I didnt properly convey the instructions, although based on your change the `bot-token` is in the secrets folder, which should be in the top level of the repo ie `discord-bot/secrets/bot-token`. Another possible issue is my `bot-token` file had a new line at the end of the only single line, and I hardcoded the removal of that new line, but your's did not (where the Nothing came from).

In the future/now im planning to make a `getToken` function so that it's easy to customize how you want your secret passed in which should make it easier to pass the token in through an environment variable like it is common on heroku or embed the token file directly into the exe.

**Comment by BorisNikulin** [comment]
O I just realized that if readFile `tokenFile` worked for you then you had no new line on the end of your token file. I should fix mine...

**Comment by SadPandaBear** [comment]
Yeah, i just followed up your instructions on ReadMe, was a bit curious with Discord.hs, used this as an example/playground and got that weird message. Thanks.

**Comment by BorisNikulin** [comment]
No prolem. Im just very confused as to where this magic new line is coming from but yeah. This is just a hello world with Discord.hs for now.
